services:
  postgres:
    image: postgres:latest
    restart: ""
    ports:
      - "2030:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
 
volumes:
  redis-data:
  postgres_database:
